[build]
  # 构建命令
  command = "npm run build"
  # 发布目录 - Next.js 静态导出的输出目录
  publish = "out"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"

# 重定向规则 - 支持 Next.js 路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
